#!/usr/bin/env python3
"""
Verify Model Bias & Accuracy

This script loads the fine-tuned model and runs inference on the validation set.
It calculates:
1. Overall Accuracy
2. Per-Family Accuracy (Precision/Recall)
3. Specific checks for 'Loader' bias (e.g., Pikabot vs IcedID)

Usage:
    python verify_model_bias.py --model models/aipam-llama --data models/aipam-llama-balanced/valid.jsonl
"""

import argparse
import json
import re
from pathlib import Path
from collections import defaultdict, Counter
from typing import Dict, List

def extract_classification_from_text(text: str) -> str:
    """Extract classification from model response text."""
    # 1. Try JSON parsing first (most robust)
    try:
        # cleanup markdown code blocks if present
        clean_text = text.replace("```json", "").replace("```", "").strip()
        data = json.loads(clean_text)
        if "classification" in data:
            # Check for attack_type or classification
            if data.get("classification") == "malicious" and data.get("attack_type"):
                return data["attack_type"]
            return data["classification"]
    except json.JSONDecodeError:
        pass

    # 2. Regex fallbacks
    # Look for JSON-like "classification": "value" pattern first
    json_match = re.search(r'"classification":\s*"([^"]+)"', text)
    if json_match:
        return json_match.group(1)
    
    # Fallback: Look for "Classification: value"
    text_match = re.search(r'Classification:\s*([^\n]+)', text, re.IGNORECASE)
    if text_match:
        return text_match.group(1).strip()
        
    return "unknown"

def load_validation_data(data_path: str) -> List[Dict]:
    """Load validation samples."""
    samples = []
    with open(data_path) as f:
        for line in f:
            try:
                data = json.loads(line)
                ground_truth = "unknown"
                instruction = ""

                # Check if it's pre-formatted text (as generated by create_balanced_dataset.py)
                if "text" in data:
                    text = data["text"]
                    # Extract User Content
                    user_part = text.split("<|start_header_id|>user<|end_header_id|>\n\n")[-1]
                    instruction = user_part.split("<|eot_id|>")[0]
                    
                    # Extract Assistant Content
                    if "<|start_header_id|>assistant<|end_header_id|>\n\n" in text:
                        assist_part = text.split("<|start_header_id|>assistant<|end_header_id|>\n\n")[-1]
                        assist_response = assist_part.split("<|eot_id|>")[0]
                        ground_truth = extract_classification_from_text(assist_response)
                
                # Check if it's structured messages (raw ChatML)
                elif "messages" in data:
                    for msg in data["messages"]:
                        if msg["role"] == "assistant":
                            ground_truth = extract_classification_from_text(msg["content"])
                        if msg["role"] == "user":
                            instruction = msg["content"]
                        
                samples.append({
                    "instruction": instruction,
                    "ground_truth": ground_truth,
                    "raw_sample": data
                })
            except json.JSONDecodeError:
                continue
    return samples

def main():
    parser = argparse.ArgumentParser(description="Verify AIPAM Model Bias")
    parser.add_argument("--model", default="models/aipam-llama", help="Path to fine-tuned model/adapter")
    parser.add_argument("--data", default="models/aipam-llama-balanced/valid.jsonl", help="Validation data path")
    parser.add_argument("--base-model", default="unsloth/llama-3.1-8b-bnb-4bit", help="Base model")
    args = parser.parse_args()

    print("=" * 60)
    print("AIPAM Model Bias Verification")
    print("=" * 60)

    # 1. Load Data
    print(f"\nLoading validation data: {args.data}")
    if not Path(args.data).exists():
        print(f"Error: Data file not found: {args.data}")
        return
        
    samples = load_validation_data(args.data)
    print(f"Loaded {len(samples)} samples.")
    
    # 2. Check for GPU (mock run if no GPU)
    gpu_available = False
    try:
        import torch
        if torch.cuda.is_available():
            gpu_available = True
    except ImportError:
        pass

    if not gpu_available:
        print("\n[WARNING] No GPU detected. Cannot run actual inference.")
        print("This script is ready to run on your GPU training machine.")
        print("\n--- Simulation Mode (Logic Check) ---")
        print("Verifying data parsing logic...")
        
        # Verify we can correctly parse ground truth from the samples
        categories = Counter()
        for s in samples:
            categories[s['ground_truth']] += 1
            
        print("\nGround Truth Distribution in Validation Set:")
        for cat, count in categories.items():
            print(f"  - {cat}: {count}")
            
        print("\n✓ Logic check complete. Run this script on a GPU machine for full verification.")
        return

    # 3. Load Model (Only runs if GPU present)
    print(f"\nLoading model: {args.model}")
    from unsloth import FastLanguageModel
    
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=args.model, # Loads adapter if present
        max_seq_length=4096,
        dtype=None,
        load_in_4bit=True,
    )
    FastLanguageModel.for_inference(model)

    # 4. Run Inference
    print("\nRunning inference...")
    correct = 0
    total = len(samples)
    y_true = []
    y_pred = []
    
    for i, sample in enumerate(samples):
        inputs = tokenizer.apply_chat_template(
            [{"role": "user", "content": sample["instruction"]}],
            tokenize=True,
            return_tensors="pt",
        ).to("cuda")

        outputs = model.generate(input_ids=inputs, max_new_tokens=256, use_cache=True)
        response_text = tokenizer.batch_decode(outputs)
        response_content = response_text[0].split("<|start_header_id|>assistant<|end_header_id|>\n\n")[-1]
        
        prediction = extract_classification_from_text(response_content)
        ground_truth = sample["ground_truth"]
        
        y_true.append(ground_truth)
        y_pred.append(prediction)
        
        is_correct = (prediction.lower() == ground_truth.lower())
        if is_correct:
            correct += 1
        
        print(f"[{i+1}/{total}] True: {ground_truth} | Pred: {prediction} | {'✓' if is_correct else '✗'}")

    # 5. Metrics
    accuracy = correct / total
    print("\n" + "=" * 60)
    print(f"Overall Accuracy: {accuracy:.2%}")
    print("=" * 60)
    
    # Per-Class Analysis
    from sklearn.metrics import classification_report
    print("\nClassification Report:")
    print(classification_report(y_true, y_pred))

if __name__ == "__main__":
    main()
