"""baseline

Revision ID: 001e6676c340
Revises: 09026eb3e663
Create Date: 2026-03-07 18:31:44.637777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '001e6676c340'
down_revision: Union[str, Sequence[str], None] = '09026eb3e663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.create_index('idx_chat_conv_job', ['job_id'], unique=False)

    op.create_table('job_pcaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.upload_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_pcaps', schema=None) as batch_op:
        batch_op.create_index('idx_job_pcaps_job', ['job_id'], unique=False)
        batch_op.create_index('idx_job_pcaps_ordinal', ['job_id', 'ordinal'], unique=False)

    op.create_table('kb_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.create_index('idx_kb_doc_job_id', ['job_id'], unique=False)
        batch_op.create_index('idx_kb_doc_status', ['status'], unique=False)
        batch_op.create_index('idx_kb_doc_type', ['doc_type'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('idx_chat_msg_conv', ['conversation_id'], unique=False)

    op.create_table('jobdb',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exercise_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'FAILED', 'COMPLETED', name='jobstatus'), nullable=False),
    sa.Column('job_metadata', sa.JSON(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobdb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobdb_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobdb_status'), ['status'], unique=False)

    op.create_table('mitrectibundledb',
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bundle_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bundle_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bundle_modified', sa.DateTime(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_table('mitretechniquedb',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('technique_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tactics', sa.JSON(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.Column('is_subtechnique', sa.Boolean(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bundle_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mitretechniquedb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mitretechniquedb_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_mitretechniquedb_technique_id'), ['technique_id'], unique=False)

    op.create_table('settingsdb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertdb',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('src_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dst_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('alert_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signature_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signature_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('flow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobdb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alertdb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertdb_dst_ip'), ['dst_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertdb_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertdb_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertdb_signature_id'), ['signature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertdb_src_ip'), ['src_ip'], unique=False)

    op.create_table('conversationdb',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobdb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversationdb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversationdb_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversationdb_job_id'), ['job_id'], unique=False)

    op.create_table('findingdb',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mitre_technique_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mitre_technique_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('affected_hosts', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('analyzer_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attack_chain_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('analyst_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('analyst_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobdb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findingdb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findingdb_analyst_status'), ['analyst_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_findingdb_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_findingdb_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findingdb_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findingdb_mitre_technique_id'), ['mitre_technique_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findingdb_severity'), ['severity'], unique=False)

    op.create_table('flowdb',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('src_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=False),
    sa.Column('dst_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dst_port', sa.Integer(), nullable=False),
    sa.Column('transport_proto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('app_proto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('bytes_from_src', sa.Integer(), nullable=False),
    sa.Column('bytes_from_dst', sa.Integer(), nullable=False),
    sa.Column('packets_from_src', sa.Integer(), nullable=False),
    sa.Column('packets_from_dst', sa.Integer(), nullable=False),
    sa.Column('tcp_flags_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobdb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flowdb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flowdb_dst_ip'), ['dst_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_flowdb_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flowdb_src_ip'), ['src_ip'], unique=False)

    op.create_table('jobresultdb',
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobdb.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('jobstepdb',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstepstatus'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobdb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobstepdb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobstepdb_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobstepdb_job_id'), ['job_id'], unique=False)

    op.create_table('partialjobresultdb',
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobdb.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('pipelinecheckpointdb',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_data', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobdb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipelinecheckpointdb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipelinecheckpointdb_job_id'), ['job_id'], unique=False)

    op.create_table('chatmessagedb',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversationdb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatmessagedb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatmessagedb_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatmessagedb_id'), ['id'], unique=False)

    op.create_table('evidencedb',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('finding_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('flow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findingdb.id'], ),
    sa.ForeignKeyConstraint(['flow_id'], ['flowdb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidencedb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidencedb_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidencedb_flow_id'), ['flow_id'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pcap_label', sa.String(), nullable=True))

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pcap_label', sa.String(), nullable=True))

    with op.batch_alter_table('dns_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pcap_label', sa.String(), nullable=True))

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pcap_label', sa.String(), nullable=True))

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pcap_label', sa.String(), nullable=True))

    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pcap_label', sa.String(), nullable=True))

    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pcap_label', sa.String(), nullable=True))

    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pcap_label', sa.String(), nullable=True))

    with op.batch_alter_table('tls_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pcap_label', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tls_sessions', schema=None) as batch_op:
        batch_op.drop_column('pcap_label')

    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_column('pcap_label')

    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.drop_column('pcap_label')
        batch_op.drop_column('context')

    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_column('pcap_label')

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_column('pcap_label')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('pcap_label')

    with op.batch_alter_table('dns_queries', schema=None) as batch_op:
        batch_op.drop_column('pcap_label')

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_column('pcap_label')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('pcap_label')

    with op.batch_alter_table('evidencedb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidencedb_flow_id'))
        batch_op.drop_index(batch_op.f('ix_evidencedb_finding_id'))

    op.drop_table('evidencedb')
    with op.batch_alter_table('chatmessagedb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatmessagedb_id'))
        batch_op.drop_index(batch_op.f('ix_chatmessagedb_conversation_id'))

    op.drop_table('chatmessagedb')
    with op.batch_alter_table('pipelinecheckpointdb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipelinecheckpointdb_job_id'))

    op.drop_table('pipelinecheckpointdb')
    op.drop_table('partialjobresultdb')
    with op.batch_alter_table('jobstepdb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobstepdb_job_id'))
        batch_op.drop_index(batch_op.f('ix_jobstepdb_id'))

    op.drop_table('jobstepdb')
    op.drop_table('jobresultdb')
    with op.batch_alter_table('flowdb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flowdb_src_ip'))
        batch_op.drop_index(batch_op.f('ix_flowdb_job_id'))
        batch_op.drop_index(batch_op.f('ix_flowdb_dst_ip'))

    op.drop_table('flowdb')
    with op.batch_alter_table('findingdb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findingdb_severity'))
        batch_op.drop_index(batch_op.f('ix_findingdb_mitre_technique_id'))
        batch_op.drop_index(batch_op.f('ix_findingdb_job_id'))
        batch_op.drop_index(batch_op.f('ix_findingdb_id'))
        batch_op.drop_index(batch_op.f('ix_findingdb_classification'))
        batch_op.drop_index(batch_op.f('ix_findingdb_analyst_status'))

    op.drop_table('findingdb')
    with op.batch_alter_table('conversationdb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversationdb_job_id'))
        batch_op.drop_index(batch_op.f('ix_conversationdb_id'))

    op.drop_table('conversationdb')
    with op.batch_alter_table('alertdb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertdb_src_ip'))
        batch_op.drop_index(batch_op.f('ix_alertdb_signature_id'))
        batch_op.drop_index(batch_op.f('ix_alertdb_severity'))
        batch_op.drop_index(batch_op.f('ix_alertdb_job_id'))
        batch_op.drop_index(batch_op.f('ix_alertdb_dst_ip'))

    op.drop_table('alertdb')
    op.drop_table('settingsdb')
    with op.batch_alter_table('mitretechniquedb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mitretechniquedb_technique_id'))
        batch_op.drop_index(batch_op.f('ix_mitretechniquedb_domain'))

    op.drop_table('mitretechniquedb')
    op.drop_table('mitrectibundledb')
    with op.batch_alter_table('jobdb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobdb_status'))
        batch_op.drop_index(batch_op.f('ix_jobdb_id'))

    op.drop_table('jobdb')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_msg_conv')

    op.drop_table('chat_messages')
    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.drop_index('idx_kb_doc_type')
        batch_op.drop_index('idx_kb_doc_status')
        batch_op.drop_index('idx_kb_doc_job_id')

    op.drop_table('kb_documents')
    with op.batch_alter_table('job_pcaps', schema=None) as batch_op:
        batch_op.drop_index('idx_job_pcaps_ordinal')
        batch_op.drop_index('idx_job_pcaps_job')

    op.drop_table('job_pcaps')
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_conv_job')

    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
