"""V2 initial schema — 13 tables

Revision ID: 09026eb3e663
Revises: 
Create Date: 2026-03-05 17:06:08.591529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09026eb3e663'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('job_name', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('execution_profile', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=True),
    sa.Column('pcap_filename', sa.Text(), nullable=True),
    sa.Column('pcap_size_bytes', sa.Integer(), nullable=True),
    sa.Column('pcap_sha256', sa.String(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('idx_jobs_created', ['created_at'], unique=False)
        batch_op.create_index('idx_jobs_profile', ['execution_profile'], unique=False)
        batch_op.create_index('idx_jobs_status', ['status'], unique=False)

    op.create_table('uploads',
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('is_valid', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('packet_count', sa.Integer(), nullable=True),
    sa.Column('capture_duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('host_ip', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sid', sa.String(), nullable=True),
    sa.Column('src_ip', sa.String(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dest_ip', sa.String(), nullable=True),
    sa.Column('dest_port', sa.Integer(), nullable=True),
    sa.Column('proto', sa.String(), nullable=True),
    sa.Column('refs_json', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('ts', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'alert_id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alerts_community', ['job_id', 'community_id'], unique=False)
        batch_op.create_index('idx_alerts_job_host', ['job_id', 'host_ip'], unique=False)
        batch_op.create_index('idx_alerts_severity', ['job_id', 'severity'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'artifact_id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index('idx_artifacts_job', ['job_id'], unique=False)

    op.create_table('connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=True),
    sa.Column('host_ip', sa.String(), nullable=False),
    sa.Column('src_ip', sa.String(), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dest_ip', sa.String(), nullable=False),
    sa.Column('dest_port', sa.Integer(), nullable=True),
    sa.Column('proto', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('bytes_sent', sa.Integer(), nullable=True),
    sa.Column('bytes_recv', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('ts', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'connection_id')
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index('idx_conn_community', ['job_id', 'community_id'], unique=False)
        batch_op.create_index('idx_conn_job_host', ['job_id', 'host_ip'], unique=False)
        batch_op.create_index('idx_conn_ts', ['job_id', 'ts'], unique=False)

    op.create_table('dns_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('dns_id', sa.String(), nullable=False),
    sa.Column('host_ip', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=True),
    sa.Column('src_ip', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('qtype', sa.String(), nullable=True),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('rcode', sa.String(), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('dest_ip', sa.String(), nullable=True),
    sa.Column('ts', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'dns_id')
    )
    with op.batch_alter_table('dns_queries', schema=None) as batch_op:
        batch_op.create_index('idx_dns_community', ['job_id', 'community_id'], unique=False)
        batch_op.create_index('idx_dns_job_host', ['job_id', 'host_ip'], unique=False)
        batch_op.create_index('idx_dns_query', ['job_id', 'query'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('host_ip', sa.String(), nullable=True),
    sa.Column('community_id', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('md5', sa.String(), nullable=True),
    sa.Column('ssdeep', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(), nullable=True),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('extracted_path', sa.Text(), nullable=True),
    sa.Column('yara_matches_json', sa.Text(), nullable=True),
    sa.Column('download_artifact_id', sa.String(), nullable=True),
    sa.Column('ts', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'file_id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index('idx_files_community', ['job_id', 'community_id'], unique=False)
        batch_op.create_index('idx_files_job', ['job_id'], unique=False)
        batch_op.create_index('idx_files_sha256', ['job_id', 'sha256'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('sensor', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('community_id', sa.String(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'finding_id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index('idx_findings_job', ['job_id'], unique=False)
        batch_op.create_index('idx_findings_sensor', ['job_id', 'sensor'], unique=False)
        batch_op.create_index('idx_findings_severity', ['job_id', 'severity'], unique=False)

    op.create_table('hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('conn_count', sa.Integer(), nullable=True),
    sa.Column('bytes_sent', sa.Integer(), nullable=True),
    sa.Column('bytes_recv', sa.Integer(), nullable=True),
    sa.Column('alert_count', sa.Integer(), nullable=True),
    sa.Column('finding_count', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.String(), nullable=True),
    sa.Column('last_seen', sa.String(), nullable=True),
    sa.Column('top_domains_json', sa.Text(), nullable=True),
    sa.Column('top_services_json', sa.Text(), nullable=True),
    sa.Column('dns_query_count', sa.Integer(), nullable=True),
    sa.Column('tls_session_count', sa.Integer(), nullable=True),
    sa.Column('alerts_by_severity_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'ip')
    )
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.create_index('idx_hosts_job', ['job_id'], unique=False)
        batch_op.create_index('idx_hosts_role', ['job_id', 'role'], unique=False)

    op.create_table('iocs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('ioc_id', sa.String(), nullable=False),
    sa.Column('ioc_type', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_sensor', sa.String(), nullable=True),
    sa.Column('sources_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'ioc_id')
    )
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.create_index('idx_iocs_job', ['job_id'], unique=False)
        batch_op.create_index('idx_iocs_type', ['job_id', 'ioc_type'], unique=False)
        batch_op.create_index('idx_iocs_value', ['value'], unique=False)

    op.create_table('job_sensors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('sensor', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('provenance_json', sa.Text(), nullable=True),
    sa.Column('stats_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'sensor')
    )
    with op.batch_alter_table('job_sensors', schema=None) as batch_op:
        batch_op.create_index('idx_job_sensors_job', ['job_id'], unique=False)

    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('ts', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index('idx_timeline_job', ['job_id'], unique=False)
        batch_op.create_index('idx_timeline_ts', ['job_id', 'ts'], unique=False)
        batch_op.create_index('idx_timeline_type', ['job_id', 'type'], unique=False)

    op.create_table('tls_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('tls_id', sa.String(), nullable=False),
    sa.Column('host_ip', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=True),
    sa.Column('src_ip', sa.String(), nullable=False),
    sa.Column('dest_ip', sa.String(), nullable=False),
    sa.Column('dest_port', sa.Integer(), nullable=True),
    sa.Column('sni', sa.String(), nullable=True),
    sa.Column('ja3', sa.String(), nullable=True),
    sa.Column('ja3s', sa.String(), nullable=True),
    sa.Column('alpn', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('cert_subject', sa.String(), nullable=True),
    sa.Column('cert_issuer', sa.String(), nullable=True),
    sa.Column('cert_fingerprint_sha1', sa.String(), nullable=True),
    sa.Column('ts', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'tls_id')
    )
    with op.batch_alter_table('tls_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_tls_community', ['job_id', 'community_id'], unique=False)
        batch_op.create_index('idx_tls_ja3', ['job_id', 'ja3'], unique=False)
        batch_op.create_index('idx_tls_job_host', ['job_id', 'host_ip'], unique=False)
        batch_op.create_index('idx_tls_sni', ['job_id', 'sni'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tls_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_tls_sni')
        batch_op.drop_index('idx_tls_job_host')
        batch_op.drop_index('idx_tls_ja3')
        batch_op.drop_index('idx_tls_community')

    op.drop_table('tls_sessions')
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index('idx_timeline_type')
        batch_op.drop_index('idx_timeline_ts')
        batch_op.drop_index('idx_timeline_job')

    op.drop_table('timeline_events')
    with op.batch_alter_table('job_sensors', schema=None) as batch_op:
        batch_op.drop_index('idx_job_sensors_job')

    op.drop_table('job_sensors')
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.drop_index('idx_iocs_value')
        batch_op.drop_index('idx_iocs_type')
        batch_op.drop_index('idx_iocs_job')

    op.drop_table('iocs')
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_index('idx_hosts_role')
        batch_op.drop_index('idx_hosts_job')

    op.drop_table('hosts')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index('idx_findings_severity')
        batch_op.drop_index('idx_findings_sensor')
        batch_op.drop_index('idx_findings_job')

    op.drop_table('findings')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('idx_files_sha256')
        batch_op.drop_index('idx_files_job')
        batch_op.drop_index('idx_files_community')

    op.drop_table('files')
    with op.batch_alter_table('dns_queries', schema=None) as batch_op:
        batch_op.drop_index('idx_dns_query')
        batch_op.drop_index('idx_dns_job_host')
        batch_op.drop_index('idx_dns_community')

    op.drop_table('dns_queries')
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index('idx_conn_ts')
        batch_op.drop_index('idx_conn_job_host')
        batch_op.drop_index('idx_conn_community')

    op.drop_table('connections')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index('idx_artifacts_job')

    op.drop_table('artifacts')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_alerts_severity')
        batch_op.drop_index('idx_alerts_job_host')
        batch_op.drop_index('idx_alerts_community')

    op.drop_table('alerts')
    op.drop_table('uploads')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_jobs_status')
        batch_op.drop_index('idx_jobs_profile')
        batch_op.drop_index('idx_jobs_created')

    op.drop_table('jobs')
    # ### end Alembic commands ###
