"""add_job_sensor_error_code

Revision ID: d1c2b579a7fc
Revises: b4c3129cd797
Create Date: 2026-03-07 21:56:38.554378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1c2b579a7fc'
down_revision: Union[str, Sequence[str], None] = 'b4c3129cd797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_code', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_sensors', schema=None) as batch_op:
        batch_op.drop_column('error_code')

    # ### end Alembic commands ###
