#!/usr/bin/env python3
"""Download and format public TI feeds into AIPAM bundle files.

Usage:
    python scripts/refresh_ti.py [--bundle-dir ti/bundles/seed]

Feeds:
    - Feodo Tracker (abuse.ch)  — botnet C2 IPs
    - SSLBL (abuse.ch)          — malicious IPs + JA3 fingerprints
    - URLhaus (abuse.ch)        — malware distribution URLs → domains & IPs
    - MalwareBazaar (abuse.ch)  — recent malware SHA256 hashes

The script writes flat text files that ``handle_ti_matcher`` in
``sensor_handlers.py`` consumes at startup.
"""

from __future__ import annotations

import argparse
import csv
import io
import re
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import urlopen, Request
from urllib.error import URLError

FEEDS: dict[str, str] = {
    "feodo_ips": "https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt",
    "sslbl_ips": "https://sslbl.abuse.ch/blacklist/sslipblacklist.txt",
    "sslbl_ja3": "https://sslbl.abuse.ch/blacklist/ja3_fingerprints.csv",
    "urlhaus_urls": "https://urlhaus.abuse.ch/downloads/text_online/",
    "bazaar_sha256": "https://bazaar.abuse.ch/export/txt/sha256/recent/",
}

_IP_RE = re.compile(
    r"^(?:(?:25[0-5]|2[0-4]\d|1?\d?\d)\.){3}(?:25[0-5]|2[0-4]\d|1?\d?\d)$"
)
_DOMAIN_RE = re.compile(r"^[a-z0-9]([a-z0-9\-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9\-]*[a-z0-9])?)+$")
_HEX32_RE = re.compile(r"^[0-9a-f]{32}$")
_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")

UA = "AIPAM-TI-Refresh/1.0"


def _fetch(url: str) -> str:
    """Fetch a URL and return its body as text."""
    req = Request(url, headers={"User-Agent": UA})
    try:
        with urlopen(req, timeout=30) as resp:
            return resp.read().decode("utf-8", errors="replace")
    except URLError as exc:
        print(f"  ⚠  Failed to fetch {url}: {exc}", file=sys.stderr)
        return ""


def _parse_plain_lines(body: str) -> list[str]:
    """Return non-empty, non-comment lines."""
    return [
        line.strip()
        for line in body.splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def _write_bundle_file(path: Path, header: str, values: set[str]) -> None:
    """Write a deduplicated, sorted bundle file."""
    with open(path, "w") as f:
        f.write(header)
        for val in sorted(values):
            f.write(val + "\n")
    print(f"  ✓ {path.name}: {len(values)} indicators")


def refresh(bundle_dir: Path) -> None:
    bundle_dir.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    ips: set[str] = set()
    domains: set[str] = set()
    ja3s: set[str] = set()
    hashes: set[str] = set()

    # ── Feodo Tracker IPs ────────────────────────────────────────────
    print("Fetching Feodo Tracker IPs …")
    for line in _parse_plain_lines(_fetch(FEEDS["feodo_ips"])):
        if _IP_RE.match(line):
            ips.add(line)

    # ── SSLBL IPs ────────────────────────────────────────────────────
    print("Fetching SSLBL IPs …")
    for line in _parse_plain_lines(_fetch(FEEDS["sslbl_ips"])):
        parts = line.split(",")
        candidate = parts[0].strip()
        if _IP_RE.match(candidate):
            ips.add(candidate)

    # ── SSLBL JA3 ────────────────────────────────────────────────────
    print("Fetching SSLBL JA3 fingerprints …")
    body = _fetch(FEEDS["sslbl_ja3"])
    reader = csv.reader(io.StringIO(body))
    for row in reader:
        if not row or row[0].startswith("#"):
            continue
        candidate = row[0].strip().lower()
        if _HEX32_RE.match(candidate):
            ja3s.add(candidate)

    # ── URLhaus URLs → domains + IPs ─────────────────────────────────
    print("Fetching URLhaus active URLs …")
    for line in _parse_plain_lines(_fetch(FEEDS["urlhaus_urls"])):
        # Extract host from URL
        match = re.match(r"https?://([^/:]+)", line)
        if not match:
            continue
        host = match.group(1).lower().rstrip(".")
        if _IP_RE.match(host):
            ips.add(host)
        elif _DOMAIN_RE.match(host):
            domains.add(host)

    # ── MalwareBazaar SHA256 hashes ──────────────────────────────────
    print("Fetching MalwareBazaar recent SHA256 hashes …")
    for line in _parse_plain_lines(_fetch(FEEDS["bazaar_sha256"])):
        candidate = line.strip().lower()
        if _SHA256_RE.match(candidate):
            hashes.add(candidate)

    # ── Write bundle files ───────────────────────────────────────────
    hdr = textwrap.dedent(f"""\
        # AIPAM Seed TI Bundle
        # Auto-generated by scripts/refresh_ti.py
        # Last updated: {now}
        #
    """)
    _write_bundle_file(bundle_dir / "ips.txt", hdr, ips)
    _write_bundle_file(bundle_dir / "domains.txt", hdr, domains)
    _write_bundle_file(bundle_dir / "ja3.txt", hdr, ja3s)
    _write_bundle_file(bundle_dir / "hashes_sha256.txt", hdr, hashes)

    # Placeholder file so ti_matcher doesn't skip it
    p = bundle_dir / "ja3s.txt"
    if not p.exists():
        _write_bundle_file(p, hdr, set())

    print(f"\nDone — bundle written to {bundle_dir}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Refresh AIPAM TI bundles")
    parser.add_argument(
        "--bundle-dir",
        type=Path,
        default=Path("ti/bundles/seed"),
        help="Directory to write bundle files into (default: ti/bundles/seed)",
    )
    args = parser.parse_args()
    refresh(args.bundle_dir)


if __name__ == "__main__":
    main()

